### ISSUE TITLE
Pattern splitting and size changing bug/inconvenience

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#17]
Splitting and expanding/shrinking a pattern (with the key shortcuts) scrolls the orderlist to POS 00 instead of keeping the current pattern highlighted.

**Comment by jpage8580** [comment]
Latest version (1.1.2) doesn't seem to have this problem. Orderlist scroll position is not reset to 0 when performing shift-K / shift-O or shift-P when in the pattern list.... for me, anyway...

**Comment by acrouzet** [comment]
Hm...it still occurs for me in the latest available win32 build.

**Comment by acrouzet** [comment]
I found a similar issue that may be related: turning follow play off and then back on again scrolls the orderlist to POS 00 too.

**Comment by jpage8580** [comment]
Fixed the cursor + follow issue. 

I've managed to repro the shift-k issue - and it happens with GTStereo too, only with specific sng files.
Possibly due to if they're using transpose or repeat info - as it works with simpler songs.

**Comment by acrouzet** [comment]
Ah, all the .sngs I've tested this with use orderlist commands.

**Comment by jpage8580** [comment]
Problem is if you use pattern $CF (same issue with the original GTStereo)

When you split a pattern, it increases all pattern numbers after the current pattern (eg. Split pattern 4 and it will move all patterns from 5 onwards up one position). And then uses pattern 5 as the new, split pattern, containing the remaining data from pattern 4.
As $CF is the last pattern, if this is used in the order list, it can not copy its data into the next pattern, $D0, as $D0 is used as REPEAT info. So no split is performed.

To make this routine more intelligent, so that it finds a spare pattern and uses that instead isn't quite as simple as it sounds.. If maybe that you've got a pattern that isn't in the order list, but does contain song data that you've just not put into a song yet.

So, what I will do is search for an empty pattern (containing nothing other than the end marker), which isn't used in any of the song/subsong order lists and use that.

**Comment by acrouzet** [comment]
The Shift+O,P,K problem is still occurring for me, and none of the .sngs that caused issues for me contained a $CF pattern.

**Comment by jpage8580** [comment]
Please send me a sng that shows this.
Thanks

**Comment by acrouzet** [comment]
Jammer's "Last Night" tune.

**Comment by jpage8580** [comment]
Added fix for changing number of SIDs and retaining current editor position settings.
Still can't repro Shift+O P,K problem though

**Comment by acrouzet** [comment]
> Still can't repro Shift+O P,K problem though
Try enabling follow play. I noticed the issue doesn't happen for me if I disable follow play before doing those commands.

**Comment by jpage8580** [comment]
Have pushed a fix (hopefully) Thanks for pointing out the follow-play info. That helped me track it down.
